name: Build and Test

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  authorize:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  build-test:
    needs: authorize
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@v0.7.1
    secrets: inherit
    
#  integration-test:
#    name: Integration Tests
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: 17
#          distribution: 'temurin'
#          cache: 'maven'
#
#      - name: Build Cache
#        uses: actions/cache@v3.0.5
#        with:
#          key: build-${{ github.run_number }}-${{ github.run_attempt }}
#          path: |
#            **/target/**
#            ~/.m2/repository/org/liquibase/
#
#      - name: Run Integration Tests
#        run: mvn -B jacoco:prepare-agent failsafe:integration-test failsafe:verify
#
#      - name: Archive Test Results
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-reports-yugabytedb
#          path: |
#            **/target/failsafe-reports
#            **/target/jacoco.exec


  dependabot:
    needs: build-test
    uses: liquibase/build-logic/.github/workflows/dependabot-automerge.yml@v0.7.1
    secrets: inherit

