name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    uses: liquibase/build-logic/.github/workflows/os-extension-test.yml@DAT-14350
    with:
      java: '[11, 17, 18]'
      trigger: ${{ github.event_name }}
    secrets: inherit
    
#  integration-test:
#    name: Integration Tests
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: 17
#          distribution: 'temurin'
#          cache: 'maven'
#
#      - name: Build Cache
#        uses: actions/cache@v3.0.5
#        with:
#          key: build-${{ github.run_number }}-${{ github.run_attempt }}
#          path: |
#            **/target/**
#            ~/.m2/repository/org/liquibase/
#
#      - name: Run Integration Tests
#        run: mvn -B jacoco:prepare-agent failsafe:integration-test failsafe:verify
#
#      - name: Archive Test Results
#        if: ${{ always() }}
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-reports-yugabytedb
#          path: |
#            **/target/failsafe-reports
#            **/target/jacoco.exec



  dependabot:
    name: Merge dependabot
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.6.0

      - name: Approve patch and minor updates
        if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: |
          gh pr merge --auto --merge "$PR_URL"
          gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a patch or minor update**"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
